### ISSUE TITLE
EBR memory barriers

### ISSUE THREAD

**Issue by charles-salvia** [rmind/libqsbr#5]
Hey - I was wondering about the full memory barriers (atomic_thread_fence with memory_order_seq_cst) in the EBR library.

Thinking about it, isn't it true that ebr_enter and ebr_exit essentially have acquire/release semantics?  Could you get away with simple acquire/release memory ordering, instead of a full memory_order_seq_cst?

It would seem that in ebr_sync, when scanning all threads, if a LOAD-acquire is used to read each local epoch, this would "synchronize-with" all release operations in ebr_exit, guaranteeing a "happens-before" relationship with the thread doing ebr_sync and all threads that have exited a critical section.

So, doesn't this imply that EBR could get away with simple acquire/release memory ordering, rather than full memory barriers with memory_order_seq_cst?

**Comment by rmind** [comment]
Not really. In addition to acquire/release semantics, `ebr_enter()` and `ebr_exit()` need stronger ordering gurantees. Consider the `ebr_enter()` case: acquire-fence would not prevent re-ordering of store to `t->local_epoch` and, for example, it might occur **after** some loads (e.g. accessing your data structure) inside the critical path. The critical path can start only after that store to the local-epoch becomes globally visible. Otherwise, the writer has an inconsistent view.

**Comment by rmind** [comment]
Resolved.
